import Header from "../components/Header";
import Info from "../components/Info";
import Section from "../components/Section";
import Products from "../components/Products";
import { productsSection } from "../constants/constant";
import {Amplify} from 'aws-amplify';

// Imports the Authenticator and withAuthenticator components from '@aws-amplify/ui-react'.
// Authenticator is a React component that provides a ready-to-use sign-in and sign-up UI.
// withAuthenticator is a higher-order component that wraps your app component to enforce authentication.
import { Authenticator, withAuthenticator } from '@aws-amplify/ui-react';

// Imports the default styles for the Amplify UI components. This line ensures that the authenticator looks nice out of the box.
import '@aws-amplify/ui-react/styles.css';

// Imports the awsExports configuration file generated by the Amplify CLI. This file contains the AWS service configurations (like Cognito, AppSync, etc.) specific to your project.
import awsExports from '../aws-exports';


// Amplify.configure({
//     Auth: {
//         region: process.env.REACT_APP_REGION,
//         userPoolId: process.env.REACT_APP_USER_POOL_ID,
//         userPoolWebClientId: process.env.REACT_APP_CLIENTID
//     }
// })
Amplify.configure(awsExports);
const Home = () => {

    return (
        <Authenticator>
            {({ signOut, user }) => (
                <>
                    <Header />
                    <Info />
                    <Section data={productsSection.iphonePro} />
                    <Section data={productsSection.iphone} />
                    <Section data={productsSection.macbookpro} />
                    <Products />
                </>
            )}
        </Authenticator>
    )
}

export default Home;